language: node_js
before_script:
  - sudo chmod 0777 ./test/bin/linux/x64/ffprobe
  - sudo cp ./test/bin/linux/x64/ffprobe /usr/bin/ffprobe
  - sudo chmod 0777 ./node_modules/.bin/mocha
  - sudo chmod 0777 ./node_modules/.bin/nyc
  - sudo chmod 0777 -R ./node_modules/mocha/lib
  - sudo chmod 0777 ./index.js
  - sudo chmod 0777 ./test/test.js
  - echo $PATH
  - ffprobe -h
script:
  - npm run test
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
sudo: required
dist: trusty
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
