language: node_js
before_script:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - sudo chmod +x -R ./scripts/
  - ./scripts/gen-output.sh
script:
  - npm run test
after_script:
  - npm run coverage
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
sudo: required
dist: trusty
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
